
/* <<< this file is on its way out 
#define ISOBURN_MAJOR_VERSION @ISOBURN_MAJOR_VERSION@
#define ISOBURN_MINOR_VERSION @ISOBURN_MINOR_VERSION@
#define ISOBURN_MICRO_VERSION @ISOBURN_MICRO_VERSION@
*/
#define LIBISOFS_MAJOR_VERSION 1
#define LIBISOFS_MINOR_VERSION 4
#define LIBISOFS_MICRO_VERSION 6
#define BURN_MAJOR_VERSION 1
#define BURN_MINOR_VERSION 4
#define BURN_MICRO_VERSION 6
